{-# LANGUAGE OverloadedStrings #-}
module IRCReply where
import Network.IRC

rpl_WELCOME :: Command
rpl_WELCOME = "001"
rpl_YOURHOST :: Command
rpl_YOURHOST = "002"
rpl_CREATED :: Command
rpl_CREATED = "003"
rpl_MYINFO :: Command
rpl_MYINFO = "004"
rpl_BOUNCE :: Command
rpl_BOUNCE = "005"
rpl_USERHOST :: Command
rpl_USERHOST = "302"
rpl_ISON :: Command
rpl_ISON = "303"
rpl_AWAY :: Command
rpl_AWAY = "301"
rpl_UNAWAY :: Command
rpl_UNAWAY = "305"
rpl_NOWAWAY :: Command
rpl_NOWAWAY = "306"
rpl_WHOISUSER :: Command
rpl_WHOISUSER = "311"
rpl_WHOISSERVER :: Command
rpl_WHOISSERVER = "312"
rpl_WHOISOPERATOR :: Command
rpl_WHOISOPERATOR = "313"
rpl_WHOISIDLE :: Command
rpl_WHOISIDLE = "317"
rpl_ENDOFWHOIS :: Command
rpl_ENDOFWHOIS = "318"
rpl_WHOISCHANNELS :: Command
rpl_WHOISCHANNELS = "319"
rpl_WHOWASUSER :: Command
rpl_WHOWASUSER = "314"
rpl_ENDOFWHOWAS :: Command
rpl_ENDOFWHOWAS = "369"
rpl_LISTSTART :: Command
rpl_LISTSTART = "321"
rpl_LIST :: Command
rpl_LIST = "322"
rpl_LISTEND :: Command
rpl_LISTEND = "323"
rpl_UNIQOPIS :: Command
rpl_UNIQOPIS = "325"
rpl_CHANNELMODEIS :: Command
rpl_CHANNELMODEIS = "324"
rpl_NOTOPIC :: Command
rpl_NOTOPIC = "331"
rpl_TOPIC :: Command
rpl_TOPIC = "332"
rpl_INVITING :: Command
rpl_INVITING = "341"
rpl_SUMMONING :: Command
rpl_SUMMONING = "342"
rpl_INVITELIST :: Command
rpl_INVITELIST = "346"
rpl_ENDOFINVITELIST :: Command
rpl_ENDOFINVITELIST = "347"
rpl_EXCEPTLIST :: Command
rpl_EXCEPTLIST = "348"
rpl_ENDOFEXCEPTLIST :: Command
rpl_ENDOFEXCEPTLIST = "349"
rpl_VERSION :: Command
rpl_VERSION = "351"
rpl_WHOREPLY :: Command
rpl_WHOREPLY = "352"
rpl_ENDOFWHO :: Command
rpl_ENDOFWHO = "315"
rpl_NAMREPLY :: Command
rpl_NAMREPLY = "353"
rpl_ENDOFNAMES :: Command
rpl_ENDOFNAMES = "366"
rpl_LINKS :: Command
rpl_LINKS = "364"
rpl_ENDOFLINKS :: Command
rpl_ENDOFLINKS = "365"
rpl_BANLIST :: Command
rpl_BANLIST = "367"
rpl_ENDOFBANLIST :: Command
rpl_ENDOFBANLIST = "368"
rpl_INFO :: Command
rpl_INFO = "371"
rpl_ENDOFINFO :: Command
rpl_ENDOFINFO = "374"
rpl_MOTDSTART :: Command
rpl_MOTDSTART = "375"
rpl_MOTD :: Command
rpl_MOTD = "372"
rpl_ENDOFMOTD :: Command
rpl_ENDOFMOTD = "376"
rpl_YOUREOPER :: Command
rpl_YOUREOPER = "381"
rpl_REHASHING :: Command
rpl_REHASHING = "382"
rpl_YOURESERVICE :: Command
rpl_YOURESERVICE = "383"
rpl_TIME :: Command
rpl_TIME = "391"
rpl_USERSSTART :: Command
rpl_USERSSTART = "392"
rpl_USERS :: Command
rpl_USERS = "393"
rpl_ENDOFUSERS :: Command
rpl_ENDOFUSERS = "394"
rpl_NOUSERS :: Command
rpl_NOUSERS = "395"
rpl_TRACELINK :: Command
rpl_TRACELINK = "200"
rpl_TRACECONNECTING :: Command
rpl_TRACECONNECTING = "201"
rpl_TRACEHANDSHAKE :: Command
rpl_TRACEHANDSHAKE = "202"
rpl_TRACEUNKNOWN :: Command
rpl_TRACEUNKNOWN = "203"
rpl_TRACEOPERATOR :: Command
rpl_TRACEOPERATOR = "204"
rpl_TRACEUSER :: Command
rpl_TRACEUSER = "205"
rpl_TRACESERVER :: Command
rpl_TRACESERVER = "206"
rpl_TRACESERVICE :: Command
rpl_TRACESERVICE = "207"
rpl_TRACENEWTYPE :: Command
rpl_TRACENEWTYPE = "208"
rpl_TRACECLASS :: Command
rpl_TRACECLASS = "209"
rpl_TRACERECONNECT :: Command
rpl_TRACERECONNECT = "210"
rpl_TRACELOG :: Command
rpl_TRACELOG = "261"
rpl_TRACEEND :: Command
rpl_TRACEEND = "262"
rpl_STATSLINKINFO :: Command
rpl_STATSLINKINFO = "211"
rpl_STATSCOMMANDS :: Command
rpl_STATSCOMMANDS = "212"
rpl_ENDOFSTATS :: Command
rpl_ENDOFSTATS = "219"
rpl_STATSUPTIME :: Command
rpl_STATSUPTIME = "242"
rpl_STATSOLINE :: Command
rpl_STATSOLINE = "243"
rpl_UMODEIS :: Command
rpl_UMODEIS = "221"
rpl_SERVLIST :: Command
rpl_SERVLIST = "234"
rpl_SERVLISTEND :: Command
rpl_SERVLISTEND = "235"
rpl_LUSERCLIENT :: Command
rpl_LUSERCLIENT = "251"
rpl_LUSEROP :: Command
rpl_LUSEROP = "252"
rpl_LUSERUNKNOWN :: Command
rpl_LUSERUNKNOWN = "253"
rpl_LUSERCHANNELS :: Command
rpl_LUSERCHANNELS = "254"
rpl_LUSERME :: Command
rpl_LUSERME = "255"
rpl_ADMINME :: Command
rpl_ADMINME = "256"
rpl_ADMINLOC1 :: Command
rpl_ADMINLOC1 = "257"
rpl_ADMINLOC2 :: Command
rpl_ADMINLOC2 = "258"
rpl_ADMINEMAIL :: Command
rpl_ADMINEMAIL = "259"
rpl_TRYAGAIN :: Command
rpl_TRYAGAIN = "263"
rpl_STATSDLINE :: Command
rpl_STATSDLINE = "250"
